# Generated by Django 5.2.4 on 2025-10-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='examsession',
            old_name='total_tokens',
            new_name='used_tokens',
        ),
        migrations.AlterUniqueTogether(
            name='examlog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_session', to='exam.examsession'),
        ),
        migrations.AddConstraint(
            model_name='examlog',
            constraint=models.UniqueConstraint(fields=('session', 'question_number'), name='unique_session_question_number'),
        ),
        migrations.AddField(
            model_name='examevaluation',
            name='exam_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='exam.examlog'),
        ),
    ]
