# Generated by Django 5.2.4 on 2025-10-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
