# Generated by Django 5.2.4 on 2025-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examsession_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='current_question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
