# Generated by Django 5.2.4 on 2025-10-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examsession_current_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exam.examsession'),
        ),
    ]
