# Generated by Django 5.2.4 on 2025-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_examlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examevaluation',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
