# Generated by Django 5.2.4 on 2025-11-04 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examevaluation_token_count'),
        ('task_management', '0010_alter_learninggoal_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='attempt_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'ct'), ('learning_goal__isnull', False)), fields=('user', 'learning_goal', 'format', 'attempt_number'), name='unique_ct_attempt_per_goal'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'mcq'), ('main_topic__isnull', False)), fields=('user', 'main_topic', 'format', 'attempt_number'), name='unique_mcq_attempt_per_main_topic'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'mcq'), ('sub_topic__isnull', False)), fields=('user', 'sub_topic', 'format', 'attempt_number'), name='unique_mcq_attempt_per_sub_topic'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'wt'), ('main_topic__isnull', False)), fields=('user', 'main_topic', 'format', 'attempt_number'), name='unique_wt_attempt_per_main_topic'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'wt'), ('main_topic__isnull', False)), fields=('user', 'sub_topic', 'format', 'attempt_number'), name='unique_wt_attempt_per_sub_topic'),
        ),
    ]
