# Generated by Django 5.2.4 on 2025-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_examsession_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='examevaluation',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='current_question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='used_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
