# Generated by Django 5.2.4 on 2025-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examsession_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='attempt_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
