# Generated by Django 5.2.4 on 2025-11-10 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_examsession_attempt_number'),
        ('task_management', '0010_alter_learninggoal_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_wt_attempt_per_sub_topic',
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'wt'), ('sub_topic__isnull', False)), fields=('user', 'sub_topic', 'format', 'attempt_number'), name='unique_wt_attempt_per_sub_topic'),
        ),
    ]
