# Generated by Django 5.2.4 on 2025-10-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturelog',
            name='role',
            field=models.CharField(choices=[('ai', 'AI'), ('user', 'USER'), ('master', 'MASTER')], max_length=10),
        ),
    ]
