# Generated by Django 5.2.4 on 2025-11-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_lecturelog_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='lecture_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
