# Generated by Django 5.2.4 on 2025-09-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_draftlearninggoal_learninggoal_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='current_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='target_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
