# Generated by Django 5.2.4 on 2025-09-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_alter_learninggoal_current_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='draft',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.draftlearninggoal'),
        ),
    ]
