# Generated by Django 5.2.4 on 2025-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_alter_learninggoal_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaintopic',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='learningsubtopic',
            name='completed',
        ),
        migrations.AlterField(
            model_name='learningmaintopic',
            name='main_topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learningsubtopic',
            name='sub_topic',
            field=models.CharField(max_length=255),
        ),
    ]
