# Generated by Django 5.2.4 on 2025-10-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_remove_learningmaintopic_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='total_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
