# Generated by Django 5.2.4 on 2025-10-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_alter_learninggoal_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='task_management.category'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='target_study_time',
            field=models.FloatField(blank=True, help_text='Target completion time(h)', null=True),
        ),
        migrations.AlterField(
            model_name='learningmaintopic',
            name='learning_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_topics', to='task_management.learninggoal'),
        ),
        migrations.AlterField(
            model_name='learningsubtopic',
            name='learning_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='task_management.learninggoal'),
        ),
    ]
