# Generated by Django 5.2.4 on 2025-11-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='main_topic',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('lec', 'Lecture'), ('mcq', 'Multiple Choice Quiz'), ('wt', 'Written Task'), ('ct', 'Comprehensive Test'), ('review', 'Review')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='time_spent',
            field=models.FloatField(blank=True, help_text='Study time in hours', null=True),
        ),
    ]
